DB_NAME = 'Giga.db'

CREATE_SCRIPT = '''
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY,
    name TEXT
);
CREATE TABLE IF NOT EXISTS gas_levels (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT,
    value REAL,
    dttm TIMESTAMP
);
CREATE TABLE IF NOT EXISTS  connection(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    cnd INTEGER,
    dttm TIMESTAMP
);
CREATE TABLE IF NOT EXISTS pressures (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT,
    value REAL,
    dttm TIMESTAMP
);
CREATE TABLE IF NOT EXISTS tank_levels (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name INTEGER,
    value INTEGER,
    dttm TIMESTAMP
);
CREATE TABLE IF NOT EXISTS pumpwork (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT,
    value INTEGER,
    dttm TIMESTAMP
);
CREATE TABLE IF NOT EXISTS bypasses(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT,
    value INTEGER,
    dttm TIMESTAMP
);
COMMIT;    
'''